# Form implementation generated from reading ui file 'vault_creation.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Raisfeld_security(object):
    def setupUi(self, Raisfeld_security):
        Raisfeld_security.setObjectName("Raisfeld_security")
        Raisfeld_security.resize(516, 504)
        Raisfeld_security.setStyleSheet("#centralwidget {background-color:rgba(20, 20, 20, 250);}\n"
"#Form {background-color:rgba(20, 20, 20, 250);}\n"
"QWidget{background-color:rgba(20, 20, 20, 250);}\n"
"\n"
"QWidget{\n"
"    color:rgba(249, 249, 249, 240);\n"
"}\n"
"\n"
"QMenuBar{background-color:rgba(20, 20, 20, 250);}\n"
"QMenu{background-color:rgba(20, 20, 20, 250);}\n"
"QMenu::item:selected{background-color:rgba(229, 229, 229, 100);}\n"
"QMenuBar::item:selected{background-color:rgba(229, 229, 229, 100);}\n"
"QListWidget{background-color:rgba(20, 20, 20, 250);}\n"
"QSpinBox{background-color:rgba(20, 20, 20, 250);}\n"
"\n"
"QMenu::separator{height:5px; background-color:rgba(191, 191, 191, 100);}\n"
"\n"
"QComboBox {\n"
"    color:rgba(193, 193, 193, 250);\n"
"    background-color:rgba(29, 29, 29, 250);\n"
"    border:none;\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"    color:rgba(193, 193, 193, 250);\n"
"    background-color:rgba(29, 29, 29, 250);\n"
"    border:none;\n"
"}\n"
"QLineEdit {\n"
"    color:rgba(193, 193, 193, 250);\n"
"    background-color:rgba(29, 29, 29, 250);\n"
"    border:none;\n"
"}\n"
"QTextEdit {\n"
"    color:rgba(193, 193, 193, 250);\n"
"    background-color:rgba(29, 29, 29, 250);\n"
"    border:none;\n"
"}\n"
"QProgressBar {\n"
"     border: 0px solid grey;\n"
"     border-radius: 0px;\n"
"     background-color:rgba(255, 255, 255, 0);\n"
"    color:rgba(255, 255, 255, 0);\n"
" }\n"
"QProgressBar::chunk\n"
"{\n"
"background-color: rgb(208, 46, 213);\n"
"}\n"
"QTableWidget {\n"
"    background-color: rgba(29, 29, 29, 250);\n"
"    color: rgba(193, 193, 193, 250);\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: rgba(50, 50, 50, 250);\n"
"}\n"
"\n"
"QTableWidget::item:focus {\n"
"    background-color: rgba(70, 70, 70, 250);\n"
"    outline: none;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgba(50, 50, 50, 250);\n"
"    color: rgba(193, 193, 193, 250);\n"
"    padding: 4px;\n"
"    border: none;\n"
"}\n"
"\n"
"QHeaderView {\n"
"    background-color: rgba(50, 50, 50, 250);\n"
"    color: rgba(193, 193, 193, 250);\n"
"    padding: 4px;\n"
"    border: none;\n"
"}\n"
"\n"
"QHeaderView::section:checked {\n"
"    background-color: rgba(70, 70, 70, 250);\n"
"}\n"
" QTableView QTableCornerButton::section {\n"
"    background-color: rgba(50, 50, 50, 250);\n"
" }\n"
"\n"
"QPushButton{background-color:rgba(59, 59, 59, 250);}\n"
"QPushButton:hover{background-color:rgba(107, 107, 107, 250);}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Raisfeld_security)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Raisfeld_security)
        font = QtGui.QFont()
        font.setFamily("Secular One")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(parent=Raisfeld_security)
        font = QtGui.QFont()
        font.setFamily("Secular One")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.Vault_name = QtWidgets.QLineEdit(parent=Raisfeld_security)
        font = QtGui.QFont()
        font.setFamily("Secular One")
        font.setPointSize(20)
        self.Vault_name.setFont(font)
        self.Vault_name.setObjectName("Vault_name")
        self.verticalLayout.addWidget(self.Vault_name, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(parent=Raisfeld_security)
        font = QtGui.QFont()
        font.setFamily("Secular One")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Select_dir = QtWidgets.QPushButton(parent=Raisfeld_security)
        font = QtGui.QFont()
        font.setFamily("Secular One")
        font.setPointSize(20)
        self.Select_dir.setFont(font)
        self.Select_dir.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Select_dir.setObjectName("Select_dir")
        self.verticalLayout.addWidget(self.Select_dir, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.Vault_dir = QtWidgets.QLabel(parent=Raisfeld_security)
        font = QtGui.QFont()
        font.setFamily("Secular One")
        font.setPointSize(18)
        self.Vault_dir.setFont(font)
        self.Vault_dir.setText("")
        self.Vault_dir.setObjectName("Vault_dir")
        self.verticalLayout.addWidget(self.Vault_dir, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.Create_vault = QtWidgets.QPushButton(parent=Raisfeld_security)
        font = QtGui.QFont()
        font.setFamily("Secular One")
        font.setPointSize(20)
        self.Create_vault.setFont(font)
        self.Create_vault.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Create_vault.setObjectName("Create_vault")
        self.verticalLayout.addWidget(self.Create_vault, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.Error = QtWidgets.QLabel(parent=Raisfeld_security)
        font = QtGui.QFont()
        font.setFamily("Secular One")
        font.setPointSize(20)
        self.Error.setFont(font)
        self.Error.setText("")
        self.Error.setObjectName("Error")
        self.verticalLayout.addWidget(self.Error, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.retranslateUi(Raisfeld_security)
        QtCore.QMetaObject.connectSlotsByName(Raisfeld_security)

    def retranslateUi(self, Raisfeld_security):
        _translate = QtCore.QCoreApplication.translate
        Raisfeld_security.setWindowTitle(_translate("Raisfeld_security", "Form"))
        self.label.setText(_translate("Raisfeld_security", "create a new vault:"))
        self.label_2.setText(_translate("Raisfeld_security", "Vault name:"))
        self.label_3.setText(_translate("Raisfeld_security", "The vault\'s file:"))
        self.Select_dir.setText(_translate("Raisfeld_security", "Select the vault\'s file"))
        self.Create_vault.setText(_translate("Raisfeld_security", "create the vault"))
